name: Generate Tree Folder Structure

on:
  workflow_dispatch:         # Allows manual trigger from GitHub UI

jobs:
  generate-structure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install tree
        run: sudo apt-get update && sudo apt-get install -y tree

      - name: Generate directory tree
        run: |
          echo '# 📁 Project Structure' > STRUCTURE.md
          echo '```' >> STRUCTURE.md
          tree -L 3 -I ".git|node_modules|.venv|__pycache__|*.md" --noreport >> STRUCTURE.md
          echo '```' >> STRUCTURE.md

      - name: Commit and push STRUCTURE.md
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add STRUCTURE.md
          git diff --quiet && git diff --staged --quiet || git commit -m "📝 Auto-generate STRUCTURE.md"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

